name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main       # your default branch
    paths:
      - 'docs/**'  # only run when files under docs/ change

permissions:
  contents: write        # allow pushing commits
  pages: write           # allow publishing to Pages
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          keep_files: false
          commit_message: "chore(docs): update GitHub Pages [skip ci]"